-- MySQL Script generated by MySQL Workbench
-- Tue Jun 11 13:03:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Lab3Part3Model
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Lab3Part3Model
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Lab3Part3Model` DEFAULT CHARACTER SET utf8 ;
USE `Lab3Part3Model` ;

-- -----------------------------------------------------
-- Table `Lab3Part3Model`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lab3Part3Model`.`Department` (
  `Department_ID` INT NOT NULL,
  `Department_Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Department_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lab3Part3Model`.`Majors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lab3Part3Model`.`Majors` (
  `Major_ID` INT NOT NULL,
  `Major_Name` VARCHAR(45) NULL,
  `Major_Department_ID` INT NULL,
  PRIMARY KEY (`Major_ID`),
  INDEX `Department_ID_idx` (`Major_Department_ID` ASC) VISIBLE,
  CONSTRAINT `Department_ID`
    FOREIGN KEY (`Major_Department_ID`)
    REFERENCES `Lab3Part3Model`.`Department` (`Department_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lab3Part3Model`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lab3Part3Model`.`Student` (
  `Student_ID` INT NOT NULL AUTO_INCREMENT,
  `Student_First_Name` VARCHAR(20) NOT NULL,
  `Student_Last_Name` VARCHAR(45) NOT NULL,
  `Student_Address` VARCHAR(45) NOT NULL,
  `Student_Major_ID` INT NULL,
  PRIMARY KEY (`Student_ID`),
  INDEX `Major_ID_idx` (`Student_Major_ID` ASC) VISIBLE,
  CONSTRAINT `Major_ID`
    FOREIGN KEY (`Student_Major_ID`)
    REFERENCES `Lab3Part3Model`.`Majors` (`Major_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lab3Part3Model`.`Faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lab3Part3Model`.`Faculty` (
  `Faculty_ID` INT NOT NULL AUTO_INCREMENT,
  `Emp_First_Name` VARCHAR(45) NULL,
  `Emp_Last_Name` VARCHAR(45) NULL,
  `Emp_Address` VARCHAR(45) NULL,
  `Emp_Department_ID` INT NULL,
  PRIMARY KEY (`Faculty_ID`),
  INDEX `Department_ID_idx` (`Emp_Department_ID` ASC) VISIBLE,
  CONSTRAINT `Department_ID`
    FOREIGN KEY (`Emp_Department_ID`)
    REFERENCES `Lab3Part3Model`.`Department` (`Department_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lab3Part3Model`.`Classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lab3Part3Model`.`Classes` (
  `Class_ID` INT NOT NULL,
  `Class_Number` INT NULL,
  `Class_Name` VARCHAR(45) NULL,
  `Class_Faculty_ID` INT NULL,
  `Class_Department_ID` INT NULL,
  PRIMARY KEY (`Class_ID`),
  INDEX `Faculty_ID_idx` (`Class_Faculty_ID` ASC) VISIBLE,
  INDEX `Department_ID_idx` (`Class_Department_ID` ASC) VISIBLE,
  CONSTRAINT `Faculty_ID`
    FOREIGN KEY (`Class_Faculty_ID`)
    REFERENCES `Lab3Part3Model`.`Faculty` (`Faculty_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Department_ID`
    FOREIGN KEY (`Class_Department_ID`)
    REFERENCES `Lab3Part3Model`.`Department` (`Department_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
